### ISSUE TITLE
Value failed for JSON property mediaInfo 

### ISSUE THREAD

**Issue by coltondick** [Schaka/janitorr#15]
It seems the error is related to the Jackson library not being able to deserialize a JSON property into the `MovieFile` class. The `mediaInfo` property is expected but missing or null in the JSON response. I'm not proficient in java, so I could be wrong.

Any suggestions to get around this error?

# Error log
```
feign.FeignException: Instantiation of [simple type, class com.github.schaka.janitorr.servarr.radarr.movie.MovieFile] value failed for JSON property mediaInfo due to missing (therefore NULL) value for creator parameter mediaInfo which is a non-nullable type
 at [Source: (BufferedReader); line: 6892, column: 5] (through reference chain: java.util.ArrayList[38]->com.github.schaka.janitorr.servarr.radarr.movie.MoviePayload["movieFile"]->com.github.schaka.janitorr.servarr.radarr.movie.MovieFile["mediaInfo"]) reading GET http://192.168.1.5:7878/api/v3/movie
        at feign.FeignException.errorReading(FeignException.java:167) ~[feign-core-13.1.jar:na]
        at feign.InvocationContext.decode(InvocationContext.java:120) ~[feign-core-13.1.jar:na]
        at feign.InvocationContext.proceed(InvocationContext.java:88) ~[feign-core-13.1.jar:na]
        at feign.ResponseHandler.handleResponse(ResponseHandler.java:63) ~[feign-core-13.1.jar:na]
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:114) ~[feign-core-13.1.jar:na]
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:70) ~[feign-core-13.1.jar:na]
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:99) ~[feign-core-13.1.jar:na]
        at jdk.proxy2/jdk.proxy2.$Proxy83.getAllMovies(Unknown Source) ~[na:na]
        at com.github.schaka.janitorr.servarr.radarr.RadarrService.getEntries(RadarrService.kt:42) ~[classes/:na]
        at com.github.schaka.janitorr.CleanupSchedule.runSchedule(CleanupSchedule.kt:41) ~[classes/:na]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130) ~[spring-context-6.1.2.jar:6.1.2]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124) ~[spring-context-6.1.2.jar:6.1.2]
        at io.micrometer.observation.Observation.observe(Observation.java:499) ~[micrometer-observation-1.12.1.jar:1.12.1]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124) ~[spring-context-6.1.2.jar:6.1.2]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.1.2.jar:6.1.2]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class com.github.schaka.janitorr.servarr.radarr.movie.MovieFile] value failed for JSON property mediaInfo due to missing (therefore NULL) value for creator parameter mediaInfo which is a non-nullable type
 at [Source: (BufferedReader); line: 6892, column: 5] (through reference chain: java.util.ArrayList[38]->com.github.schaka.janitorr.servarr.radarr.movie.MoviePayload["movieFile"]->com.github.schaka.janitorr.servarr.radarr.movie.MovieFile["mediaInfo"])
        at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:84) ~[jackson-module-kotlin-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:525) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1409) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:545) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:570) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1409) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3801) ~[jackson-databind-2.15.3.jar:2.15.3]
        at feign.jackson.JacksonDecoder.decode(JacksonDecoder.java:65) ~[feign-jackson-13.1.jar:na]
        at feign.InvocationContext.decode(InvocationContext.java:114) ~[feign-core-13.1.jar:na]
        ... 21 common frames omitted
```

**Comment by Schaka** [comment]
I'm curious how you're running into so many issues that I haven't seen on either of my libraries. I have a combined library of about 60TB, albeit more TV shows than movies.

Do you run an unstable version of Radarr or maybe something older?

Appreciate you for reporting all of these. I'm turning it nullable, as it's currently not in use.
To explain a little: Kotlin assumes non-nullability by default, to make things nullable, you'd change the type to include a `?`.

My classes are generated from the Radarr API docs and will sometimes contain some properties that I don't actively use but left in for debugging purposes. It's extremely useful being able to see ALL info regarding certain media items when debugging. If you encounter any more of these, don't hesitate to report them. I'll have them fixed within hours.

**Comment by coltondick** [comment]
Awesome thanks for the quick response!

I've got around the same sized library. 

I'm running the following versions: 
Radarr 5.3.6.8612
Sonarr 4.0.2.1183

Which appear to be the latest version of both Radarr and Sonarr.

**Comment by coltondick** [comment]
I just tried the latest version and I am now presented with the following error: 

```
2024-03-05T16:20:07.223Z  INFO 1 --- [   scheduling-1] c.g.s.j.servarr.sonarr.SonarrService     : Deleting /tv/Virgin River - episode 2 (30700) of season 5
2024-03-05T16:20:07.223Z  INFO 1 --- [   scheduling-1] c.g.s.j.servarr.sonarr.SonarrService     : Deleting /tv/Virgin River - episode 3 (30701) of season 5
2024-03-05T16:20:07.223Z  INFO 1 --- [   scheduling-1] c.g.s.j.servarr.sonarr.SonarrService     : Deleting /tv/Virgin River - episode 4 (30702) of season 5
2024-03-05T16:20:07.223Z  INFO 1 --- [   scheduling-1] c.g.s.j.servarr.sonarr.SonarrService     : Deleting /tv/Virgin River - episode 5 (30703) of season 5
2024-03-05T16:20:07.223Z  INFO 1 --- [   scheduling-1] c.g.s.j.servarr.sonarr.SonarrService     : Deleting /tv/Virgin River - episode 6 (30704) of season 5
2024-03-05T16:20:07.223Z  INFO 1 --- [   scheduling-1] c.g.s.j.servarr.sonarr.SonarrService     : Deleting /tv/Virgin River - episode 7 (30705) of season 5
2024-03-05T16:20:07.223Z  INFO 1 --- [   scheduling-1] c.g.s.j.servarr.sonarr.SonarrService     : Deleting /tv/Virgin River - episode 8 (30706) of season 5
2024-03-05T16:20:07.223Z  INFO 1 --- [   scheduling-1] c.g.s.j.servarr.sonarr.SonarrService     : Deleting /tv/Virgin River - episode 9 (30707) of season 5
2024-03-05T16:20:07.223Z  INFO 1 --- [   scheduling-1] c.g.s.j.servarr.sonarr.SonarrService     : Deleting /tv/Virgin River - episode 10 (30708) of season 5
2024-03-05T16:20:07.223Z  INFO 1 --- [   scheduling-1] c.g.s.j.servarr.sonarr.SonarrService     : Deleting /tv/Virgin River - episode 11 (30709) of season 5
2024-03-05T16:20:07.223Z  INFO 1 --- [   scheduling-1] c.g.s.j.servarr.sonarr.SonarrService     : Deleting /tv/Virgin River - episode 12 (30710) of season 5
2024-03-05T16:20:09.358Z ERROR 1 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

java.lang.NullPointerException: null
        at com.github.schaka.janitorr.servarr.radarr.RadarrService.getEntries(RadarrService.kt:50) ~[classes/:na]
        at com.github.schaka.janitorr.CleanupSchedule.runSchedule(CleanupSchedule.kt:41) ~[classes/:na]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130) ~[spring-context-6.1.2.jar:6.1.2]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124) ~[spring-context-6.1.2.jar:6.1.2]
        at io.micrometer.observation.Observation.observe(Observation.java:499) ~[micrometer-observation-1.12.1.jar:1.12.1]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124) ~[spring-context-6.1.2.jar:6.1.2]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.1.2.jar:6.1.2]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

**Comment by Schaka** [comment]
It seems that your Radarr history contains a history where
`eventType` is `downloadFolderImported` but the movieFile doesn't exist for some reason.

It seems there's a state in which a movie can be listed as having a downloaded file in the history, but currently does NOT actually have a file attached. Should be an easy fix. 

I wanted to appreciate my gratitude. You're really helping me iron out edge cases I had no idea were even a thing.

**Comment by coltondick** [comment]
No worries. You've been incredibly responsive to my issues. 

The changes you've implemented have got me past the previous error. However, now I am receiving an error with providerIds 

```
feign.FeignException: Cannot deserialize value of type `java.lang.Integer` from String "4513-30-days-of-night": not a valid `java.lang.Integer` value
 at [Source: (BufferedReader); line: 1, column: 754719] (through reference chain: com.github.schaka.janitorr.jellyfin.library.items.ItemPage["Items"]->java.util.ArrayList[568]->com.github.schaka.janitorr.jellyfin.library.LibraryContent["ProviderIds"]->com.github.schaka.janitorr.jellyfin.library.ProviderIds["Tmdb"]) reading GET https://jellyfin.colton.sh/Items?limit=10000&includeItemTypes=Movies&parentId=f137a2dd21bbc1b99aa5c0f6bf02a805&fields=Path&fields=ProviderIds
        at feign.FeignException.errorReading(FeignException.java:167) ~[feign-core-13.1.jar:na]
        at feign.InvocationContext.decode(InvocationContext.java:120) ~[feign-core-13.1.jar:na]
        at feign.InvocationContext.proceed(InvocationContext.java:88) ~[feign-core-13.1.jar:na]
        at feign.ResponseHandler.handleResponse(ResponseHandler.java:63) ~[feign-core-13.1.jar:na]
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:114) ~[feign-core-13.1.jar:na]
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:70) ~[feign-core-13.1.jar:na]
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:99) ~[feign-core-13.1.jar:na]
        at jdk.proxy2/jdk.proxy2.$Proxy75.getAllMovies(Unknown Source) ~[na:na]
        at com.github.schaka.janitorr.jellyfin.JellyfinRestService.cleanupMovies(JellyfinRestService.kt:66) ~[classes/:na]
        at com.github.schaka.janitorr.CleanupSchedule.deleteMovies(CleanupSchedule.kt:56) ~[classes/:na]
        at com.github.schaka.janitorr.CleanupSchedule.runSchedule(CleanupSchedule.kt:46) ~[classes/:na]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130) ~[spring-context-6.1.2.jar:6.1.2]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124) ~[spring-context-6.1.2.jar:6.1.2]
        at io.micrometer.observation.Observation.observe(Observation.java:499) ~[micrometer-observation-1.12.1.jar:1.12.1]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124) ~[spring-context-6.1.2.jar:6.1.2]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.1.2.jar:6.1.2]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Integer` from String "4513-30-days-of-night": not a valid `java.lang.Integer` value
 at [Source: (BufferedReader); line: 1, column: 754719] (through reference chain: com.github.schaka.janitorr.jellyfin.library.items.ItemPage["Items"]->java.util.ArrayList[568]->com.github.schaka.janitorr.jellyfin.library.LibraryContent["ProviderIds"]->com.github.schaka.janitorr.jellyfin.library.ProviderIds["Tmdb"])
        at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:2002) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:1230) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseInteger(StdDeserializer.java:844) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseInteger(StdDeserializer.java:824) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:531) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:506) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:545) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:570) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1409) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:545) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:570) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1409) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:545) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:570) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1409) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825) ~[jackson-databind-2.15.3.jar:2.15.3]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3801) ~[jackson-databind-2.15.3.jar:2.15.3]
        at feign.jackson.JacksonDecoder.decode(JacksonDecoder.java:65) ~[feign-jackson-13.1.jar:na]
        at feign.InvocationContext.decode(InvocationContext.java:114) ~[feign-core-13.1.jar:na]
        ... 22 common frames omitted
        ```

**Comment by Schaka** [comment]
That problem seems to be, because Jellyfin is using incorrect metadata.
TMDB and TVDB should be integer.

Here's an example from my library:
![image](https://github.com/Schaka/janitorr/assets/2223171/73d60f76-8b6b-4861-b46a-55574e4f770d)

I can potentially fix this by just treating both as strings. But I'd be curious why yours is so wrong. It seems almost like it's just using the path from TMDB instead of the ID.

**Comment by coltondick** [comment]
I've edited the metadata for this movie and everything appears to be working now. Thanks again for all the help getting this working!
