### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by nothing2obvi** [Schaka/janitorr#19]
Hello. We talked on Reddit earlier and while I'm grateful for your help, I still need help getting this set up. I disabled media deletion and am only using tag deletion. I don't quite understand the "minimum-free-disk-percent" parameter. I set it to 50 just to experiment and I receive the following error. I tried using "localhost" and I also tried "10.0.0.94" which is my local IP, thinking that had something to do with it.

In the `application.yml` file I created a tag named "1d" and set the expiration for 1d, then I tagged just one show on Sonarr with the tag "1d" just to test this out.

Any suggestions? Thanks.

```
03/17/2024
12:39:43 PM
2024-03-17T19:39:43.247Z  INFO 1 --- [           main] c.g.s.janitorr.JanitorrApplicationKt     : Starting JanitorrApplicationKt using Java 21.0.2 with PID 1 (/app/classes started by root in /)
03/17/2024
12:39:43 PM
2024-03-17T19:39:43.249Z DEBUG 1 --- [           main] c.g.s.janitorr.JanitorrApplicationKt     : Running with Spring Boot v3.2.2, Spring v6.1.3
03/17/2024
12:39:43 PM
2024-03-17T19:39:43.249Z  INFO 1 --- [           main] c.g.s.janitorr.JanitorrApplicationKt     : No active profile set, falling back to 1 default profile: "default"
03/17/2024
12:39:44 PM
2024-03-17T19:39:44.328Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8978 (http)
03/17/2024
12:39:44 PM
2024-03-17T19:39:44.339Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
03/17/2024
12:39:44 PM
2024-03-17T19:39:44.339Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.18]
03/17/2024
12:39:44 PM
2024-03-17T19:39:44.375Z  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
03/17/2024
12:39:44 PM
2024-03-17T19:39:44.375Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1087 ms
03/17/2024
12:39:44 PM
Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
03/17/2024
12:39:45 PM
2024-03-17T19:39:45.393Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8978 (http) with context path ''
03/17/2024
12:39:45 PM
2024-03-17T19:39:45.407Z  INFO 1 --- [           main] c.g.s.janitorr.JanitorrApplicationKt     : Started JanitorrApplicationKt in 2.624 seconds (process running for 3.116)
03/17/2024
12:39:49 PM
2024-03-17T19:39:49.971Z ERROR 1 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
03/17/2024
12:39:49 PM
03/17/2024
12:39:49 PM
feign.FeignException: Instantiation of [simple type, class com.github.schaka.janitorr.servarr.sonarr.series.SeriesPayload] value failed for JSON property originalLanguage due to missing (therefore NULL) value for creator parameter originalLanguage which is a non-nullable type
03/17/2024
12:39:49 PM
 at [Source: (BufferedReader); line: 108, column: 3] (through reference chain: java.util.ArrayList[0]->com.github.schaka.janitorr.servarr.sonarr.series.SeriesPayload["originalLanguage"]) reading GET http://10.0.0.94:8989/api/v3/series
03/17/2024
12:39:49 PM
	at feign.FeignException.errorReading(FeignException.java:167) ~[feign-core-13.1.jar:na]
03/17/2024
12:39:49 PM
	at feign.InvocationContext.decode(InvocationContext.java:120) ~[feign-core-13.1.jar:na]
03/17/2024
12:39:49 PM
	at feign.InvocationContext.proceed(InvocationContext.java:88) ~[feign-core-13.1.jar:na]
03/17/2024
12:39:49 PM
	at feign.ResponseHandler.handleResponse(ResponseHandler.java:63) ~[feign-core-13.1.jar:na]
03/17/2024
12:39:49 PM
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:114) ~[feign-core-13.1.jar:na]
03/17/2024
12:39:49 PM
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:70) ~[feign-core-13.1.jar:na]
03/17/2024
12:39:49 PM
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:99) ~[feign-core-13.1.jar:na]
03/17/2024
12:39:49 PM
	at jdk.proxy2/jdk.proxy2.$Proxy82.getAllSeries(Unknown Source) ~[na:na]
03/17/2024
12:39:49 PM
	at com.github.schaka.janitorr.servarr.sonarr.SonarrService.getEntries(SonarrService.kt:50) ~[classes/:na]
03/17/2024
12:39:49 PM
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
03/17/2024
12:39:49 PM
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
03/17/2024
12:39:49 PM
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351) ~[spring-aop-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:64) ~[spring-context-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:416) ~[spring-context-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.cache.interceptor.CacheAspectSupport.evaluate(CacheAspectSupport.java:545) ~[spring-context-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:433) ~[spring-context-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:395) ~[spring-context-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:74) ~[spring-context-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717) ~[spring-aop-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at com.github.schaka.janitorr.servarr.sonarr.SonarrService$$SpringCGLIB$$0.getEntries(<generated>) ~[classes/:na]
03/17/2024
12:39:49 PM
	at com.github.schaka.janitorr.cleanup.AbstractCleanupSchedule.cleanupMediaType(AbstractCleanupSchedule.kt:66) ~[classes/:na]
03/17/2024
12:39:49 PM
	at com.github.schaka.janitorr.cleanup.AbstractCleanupSchedule.scheduleDelete(AbstractCleanupSchedule.kt:46) ~[classes/:na]
03/17/2024
12:39:49 PM
	at com.github.schaka.janitorr.cleanup.TagBasedCleanupSchedule.runSchedule(TagBasedCleanupSchedule.kt:46) ~[classes/:na]
03/17/2024
12:39:49 PM
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
03/17/2024
12:39:49 PM
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
03/17/2024
12:39:49 PM
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351) ~[spring-aop-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:64) ~[spring-context-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:416) ~[spring-context-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.cache.interceptor.CacheAspectSupport.evaluate(CacheAspectSupport.java:545) ~[spring-context-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:433) ~[spring-context-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:395) ~[spring-context-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:74) ~[spring-context-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717) ~[spring-aop-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at com.github.schaka.janitorr.cleanup.TagBasedCleanupSchedule$$SpringCGLIB$$0.runSchedule(<generated>) ~[classes/:na]
03/17/2024
12:39:49 PM
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
03/17/2024
12:39:49 PM
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
03/17/2024
12:39:49 PM
	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130) ~[spring-context-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124) ~[spring-context-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at io.micrometer.observation.Observation.observe(Observation.java:499) ~[micrometer-observation-1.12.2.jar:1.12.2]
03/17/2024
12:39:49 PM
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124) ~[spring-context-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.1.3.jar:6.1.3]
03/17/2024
12:39:49 PM
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
03/17/2024
12:39:49 PM
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na]
03/17/2024
12:39:49 PM
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
03/17/2024
12:39:49 PM
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
03/17/2024
12:39:49 PM
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
03/17/2024
12:39:49 PM
	at java.base/java.lang.VirtualThread.run(Unknown Source) ~[na:na]
03/17/2024
12:39:49 PM
Caused by: com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class com.github.schaka.janitorr.servarr.sonarr.series.SeriesPayload] value failed for JSON property originalLanguage due to missing (therefore NULL) value for creator parameter originalLanguage which is a non-nullable type
03/17/2024
12:39:49 PM
 at [Source: (BufferedReader); line: 108, column: 3] (through reference chain: java.util.ArrayList[0]->com.github.schaka.janitorr.servarr.sonarr.series.SeriesPayload["originalLanguage"])
03/17/2024
12:39:49 PM
	at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:84) ~[jackson-module-kotlin-2.15.3.jar:2.15.3]
03/17/2024
12:39:49 PM
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202) ~[jackson-databind-2.15.3.jar:2.15.3]
03/17/2024
12:39:49 PM
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:525) ~[jackson-databind-2.15.3.jar:2.15.3]
03/17/2024
12:39:49 PM
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1409) ~[jackson-databind-2.15.3.jar:2.15.3]
03/17/2024
12:39:49 PM
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[jackson-databind-2.15.3.jar:2.15.3]
03/17/2024
12:39:49 PM
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.15.3.jar:2.15.3]
03/17/2024
12:39:49 PM
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359) ~[jackson-databind-2.15.3.jar:2.15.3]
03/17/2024
12:39:49 PM
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[jackson-databind-2.15.3.jar:2.15.3]
03/17/2024
12:39:49 PM
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[jackson-databind-2.15.3.jar:2.15.3]
03/17/2024
12:39:49 PM
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.15.3.jar:2.15.3]
03/17/2024
12:39:49 PM
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825) ~[jackson-databind-2.15.3.jar:2.15.3]
03/17/2024
12:39:49 PM
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3801) ~[jackson-databind-2.15.3.jar:2.15.3]
03/17/2024
12:39:49 PM
	at feign.jackson.JacksonDecoder.decode(JacksonDecoder.java:65) ~[feign-jackson-13.1.jar:na]
03/17/2024
12:39:49 PM
	at feign.InvocationContext.decode(InvocationContext.java:114) ~[feign-core-13.1.jar:na]
03/17/2024
12:39:49 PM
	... 55 common frames omitted
```

**Comment by Schaka** [comment]
Are you using sonarr v3?
Only v4 is supported.

It seems there's a field that it can't find in the API. While I can make that field optional, it's important to understand why it seems to be missing in the first place.
