### ISSUE TITLE
Error after upgrading to 1.0.4

### ISSUE THREAD

**Issue by sjafferali** [Schaka/janitorr#21]
Ahoy there. I just upgraded to 1.0.4 and after updating my configuration, am receiving the below error. 

```
2024-03-20T13:08:11.455320410Z 2024-03-20T13:08:11.455Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.18]
2024-03-20T13:08:11.485567785Z 2024-03-20T13:08:11.485Z  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-03-20T13:08:11.486382654Z 2024-03-20T13:08:11.486Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 851 ms
2024-03-20T13:08:11.487862445Z Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
2024-03-20T13:08:12.119473297Z 2024-03-20T13:08:12.119Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8978 (http) with context path ''
2024-03-20T13:08:12.131790826Z 2024-03-20T13:08:12.131Z  INFO 1 --- [           main] c.g.s.janitorr.JanitorrApplicationKt     : Started JanitorrApplicationKt in 1.819 seconds (process running for 2.014)
2024-03-20T13:08:12.270964944Z 2024-03-20T13:08:12.267Z ERROR 1 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
2024-03-20T13:08:12.270990210Z 
2024-03-20T13:08:12.270992599Z feign.FeignException: Instantiation of [simple type, class com.github.schaka.janitorr.servarr.radarr.movie.Quality] value failed for JSON property modifier due to missing (therefore NULL) value for creator parameter modifier which is a non-nullable type
2024-03-20T13:08:12.271005479Z  at [Source: (BufferedReader); line: 18, column: 7] (through reference chain: java.util.ArrayList[0]->com.github.schaka.janitorr.servarr.history.HistoryResponse["quality"]->com.github.schaka.janitorr.servarr.radarr.movie.QualityWrapper["quality"]->com.github.schaka.janitorr.servarr.radarr.movie.Quality["modifier"]) reading GET http://172.25.10.131:8989/api/v3/history/series?seriesId=2&seasonNumber=1
2024-03-20T13:08:12.271008717Z 	at feign.FeignException.errorReading(FeignException.java:167) ~[feign-core-13.1.jar:na]
2024-03-20T13:08:12.271010887Z 	at feign.InvocationContext.decode(InvocationContext.java:120) ~[feign-core-13.1.jar:na]
2024-03-20T13:08:12.271012806Z 	at feign.InvocationContext.proceed(InvocationContext.java:88) ~[feign-core-13.1.jar:na]
2024-03-20T13:08:12.271014489Z 	at feign.ResponseHandler.handleResponse(ResponseHandler.java:63) ~[feign-core-13.1.jar:na]
2024-03-20T13:08:12.271016261Z 	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:114) ~[feign-core-13.1.jar:na]
2024-03-20T13:08:12.271018052Z 	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:70) ~[feign-core-13.1.jar:na]
2024-03-20T13:08:12.271019696Z 	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:99) ~[feign-core-13.1.jar:na]
2024-03-20T13:08:12.271021540Z 	at jdk.proxy2/jdk.proxy2.$Proxy82.getHistory(Unknown Source) ~[na:na]
2024-03-20T13:08:12.271023168Z 	at com.github.schaka.janitorr.servarr.sonarr.SonarrService.getEntries(SonarrService.kt:54) ~[classes/:na]
2024-03-20T13:08:12.271024939Z 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
2024-03-20T13:08:12.271026719Z 	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
2024-03-20T13:08:12.271028346Z 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351) ~[spring-aop-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271030719Z 	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271032505Z 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271034263Z 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271035963Z 	at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:64) ~[spring-context-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271037636Z 	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:416) ~[spring-context-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271039472Z 	at org.springframework.cache.interceptor.CacheAspectSupport.evaluate(CacheAspectSupport.java:545) ~[spring-context-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271041281Z 	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:433) ~[spring-context-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271045272Z 	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:395) ~[spring-context-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271047074Z 	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:74) ~[spring-context-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271048725Z 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271050577Z 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271052290Z 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717) ~[spring-aop-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271054233Z 	at com.github.schaka.janitorr.servarr.sonarr.SonarrService$$SpringCGLIB$$0.getEntries(<generated>) ~[classes/:na]
2024-03-20T13:08:12.271055980Z 	at com.github.schaka.janitorr.cleanup.AbstractCleanupSchedule.cleanupMediaType(AbstractCleanupSchedule.kt:66) ~[classes/:na]
2024-03-20T13:08:12.271057863Z 	at com.github.schaka.janitorr.cleanup.AbstractCleanupSchedule.scheduleDelete(AbstractCleanupSchedule.kt:46) ~[classes/:na]
2024-03-20T13:08:12.271059714Z 	at com.github.schaka.janitorr.cleanup.AbstractCleanupSchedule.scheduleDelete$default(AbstractCleanupSchedule.kt:30) ~[classes/:na]
2024-03-20T13:08:12.271061619Z 	at com.github.schaka.janitorr.cleanup.MediaCleanupSchedule.runSchedule(MediaCleanupSchedule.kt:46) ~[classes/:na]
2024-03-20T13:08:12.271063443Z 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
2024-03-20T13:08:12.271065183Z 	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
2024-03-20T13:08:12.271066785Z 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351) ~[spring-aop-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271068585Z 	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271070371Z 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271072139Z 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271073933Z 	at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:64) ~[spring-context-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271075582Z 	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:416) ~[spring-context-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271077427Z 	at org.springframework.cache.interceptor.CacheAspectSupport.evaluate(CacheAspectSupport.java:545) ~[spring-context-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271079260Z 	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:433) ~[spring-context-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271082520Z 	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:395) ~[spring-context-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271084379Z 	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:74) ~[spring-context-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271086107Z 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271087980Z 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271089810Z 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717) ~[spring-aop-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271091701Z 	at com.github.schaka.janitorr.cleanup.MediaCleanupSchedule$$SpringCGLIB$$0.runSchedule(<generated>) ~[classes/:na]
2024-03-20T13:08:12.271093568Z 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
2024-03-20T13:08:12.271095288Z 	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
2024-03-20T13:08:12.271096904Z 	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130) ~[spring-context-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271098771Z 	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124) ~[spring-context-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271100595Z 	at io.micrometer.observation.Observation.observe(Observation.java:499) ~[micrometer-observation-1.12.2.jar:1.12.2]
2024-03-20T13:08:12.271102314Z 	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124) ~[spring-context-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271104126Z 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.1.3.jar:6.1.3]
2024-03-20T13:08:12.271105927Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
2024-03-20T13:08:12.271107525Z 	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na]
2024-03-20T13:08:12.271109366Z 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
2024-03-20T13:08:12.271111162Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
2024-03-20T13:08:12.271112756Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
2024-03-20T13:08:12.271114565Z 	at java.base/java.lang.VirtualThread.run(Unknown Source) ~[na:na]
2024-03-20T13:08:12.271116564Z Caused by: com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class com.github.schaka.janitorr.servarr.radarr.movie.Quality] value failed for JSON property modifier due to missing (therefore NULL) value for creator parameter modifier which is a non-nullable type
2024-03-20T13:08:12.271118620Z  at [Source: (BufferedReader); line: 18, column: 7] (through reference chain: java.util.ArrayList[0]->com.github.schaka.janitorr.servarr.history.HistoryResponse["quality"]->com.github.schaka.janitorr.servarr.radarr.movie.QualityWrapper["quality"]->com.github.schaka.janitorr.servarr.radarr.movie.Quality["modifier"])
2024-03-20T13:08:12.271122472Z 	at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:84) ~[jackson-module-kotlin-2.15.3.jar:2.15.3]
2024-03-20T13:08:12.271124293Z 	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202) ~[jackson-databind-2.15.3.jar:2.15.3]
2024-03-20T13:08:12.271125942Z 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:525) ~[jackson-databind-2.15.3.jar:2.15.3]
2024-03-20T13:08:12.271127927Z 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1409) ~[jackson-databind-2.15.3.jar:2.15.3]
2024-03-20T13:08:12.271129751Z 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[jackson-databind-2.15.3.jar:2.15.3]
2024-03-20T13:08:12.271131407Z 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.15.3.jar:2.15.3]
2024-03-20T13:08:12.271133408Z 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:545) ~[jackson-databind-2.15.3.jar:2.15.3]
2024-03-20T13:08:12.271135174Z 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:570) ~[jackson-databind-2.15.3.jar:2.15.3]
2024-03-20T13:08:12.271137063Z 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439) ~[jackson-databind-2.15.3.jar:2.15.3]
2024-03-20T13:08:12.271138775Z 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1409) ~[jackson-databind-2.15.3.jar:2.15.3]
2024-03-20T13:08:12.271140629Z 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[jackson-databind-2.15.3.jar:2.15.3]
2024-03-20T13:08:12.271142324Z 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.15.3.jar:2.15.3]
2024-03-20T13:08:12.271144143Z 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:545) ~[jackson-databind-2.15.3.jar:2.15.3]
2024-03-20T13:08:12.271146141Z 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:570) ~[jackson-databind-2.15.3.jar:2.15.3]
2024-03-20T13:08:12.271147901Z 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439) ~[jackson-databind-2.15.3.jar:2.15.3]
2024-03-20T13:08:12.271149768Z 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1409) ~[jackson-databind-2.15.3.jar:2.15.3]
2024-03-20T13:08:12.271151591Z 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[jackson-databind-2.15.3.jar:2.15.3]
2024-03-20T13:08:12.271155162Z 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.15.3.jar:2.15.3]
2024-03-20T13:08:12.271156861Z 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359) ~[jackson-databind-2.15.3.jar:2.15.3]
2024-03-20T13:08:12.271158779Z 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[jackson-databind-2.15.3.jar:2.15.3]
2024-03-20T13:08:12.271160857Z 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[jackson-databind-2.15.3.jar:2.15.3]
2024-03-20T13:08:12.271162809Z 	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.15.3.jar:2.15.3]
2024-03-20T13:08:12.271164483Z 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825) ~[jackson-databind-2.15.3.jar:2.15.3]
2024-03-20T13:08:12.271166240Z 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3801) ~[jackson-databind-2.15.3.jar:2.15.3]
2024-03-20T13:08:12.271167891Z 	at feign.jackson.JacksonDecoder.decode(JacksonDecoder.java:65) ~[feign-jackson-13.1.jar:na]
2024-03-20T13:08:12.271169696Z 	at feign.InvocationContext.decode(InvocationContext.java:114) ~[feign-core-13.1.jar:na]
2024-03-20T13:08:12.271171459Z 	... 56 common frames omitted
```

**Comment by Schaka** [comment]
Interesting. I didn't change the field itself (i.e. it's nullability). I only renamed the type.
Tried to unify it a bit more between the two and do some cleanup. 

Thanks for the report, will be fixed in 1.0.5 in a second.
