### ISSUE TITLE
Problem running Janitorr

### ISSUE THREAD

**Issue by Sergiomg86** [Schaka/janitorr#39]
In the log it seems that it is not able to start Janitorr, I don't know why, I don't know if the connection with Jellyseer fails but all my data is ok.

LOG 
```
time="2024-05-15T14:07:39+02:00" level=warning msg="/compose/janitorr/janitorr.yml: `version` is obsolete"
janitorr  | 
janitorr  |   .   ____          _            __ _ _
janitorr  |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
janitorr  | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
janitorr  |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
janitorr  |   '  |____| .__|_| |_|_| |_\__, | / / / /
janitorr  |  =========|_|==============|___/=/_/_/_/
janitorr  |  :: Spring Boot ::                (v3.2.4)
janitorr  | 
janitorr  | 2024-05-15T14:05:54.079+02:00  INFO 1 --- [           main] c.g.s.janitorr.JanitorrApplicationKt     : Starting JanitorrApplicationKt using Java 21.0.2 with PID 1 (/app/classes started by root in /)
janitorr  | 2024-05-15T14:05:54.083+02:00  INFO 1 --- [           main] c.g.s.janitorr.JanitorrApplicationKt     : No active profile set, falling back to 1 default profile: "default"
janitorr  | 2024-05-15T14:05:55.833+02:00  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8978 (http)
janitorr  | 2024-05-15T14:05:55.851+02:00  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
janitorr  | 2024-05-15T14:05:55.851+02:00  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.19]
janitorr  | 2024-05-15T14:05:55.911+02:00  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
janitorr  | 2024-05-15T14:05:55.913+02:00  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1719 ms
janitorr  | 2024-05-15T14:06:47.658+02:00  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mediaCleanupSchedule' defined in file [/app/classes/com/github/schaka/janitorr/cleanup/MediaCleanupSchedule.class]: Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'jellyseerrService' defined in class path resource [com/github/schaka/janitorr/jellyseerr/JellyseerrConfig.class]: Failed to instantiate [com.github.schaka.janitorr.jellyseerr.JellyseerrService]: Factory method 'jellyseerrService' threw exception with message: Connect timed out executing GET http://192.168.80.2:5055/api/v1/settings/radarr
janitorr  | 2024-05-15T14:06:47.662+02:00  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
janitorr  | 2024-05-15T14:06:47.690+02:00  INFO 1 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 
janitorr  | 
janitorr  | Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
janitorr  | 2024-05-15T14:06:47.715+02:00 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
janitorr  | 
janitorr  | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mediaCleanupSchedule' defined in file [/app/classes/com/github/schaka/janitorr/cleanup/MediaCleanupSchedule.class]: Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'jellyseerrService' defined in class path resource [com/github/schaka/janitorr/jellyseerr/JellyseerrConfig.class]: Failed to instantiate [com.github.schaka.janitorr.jellyseerr.JellyseerrService]: Factory method 'jellyseerrService' threw exception with message: Connect timed out executing GET http://192.168.80.2:5055/api/v1/settings/radarr
janitorr  | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:795) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:237) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1355) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1192) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:962) ~[spring-context-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624) ~[spring-context-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.4.jar:3.2.4]
janitorr  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.2.4.jar:3.2.4]
janitorr  | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.2.4.jar:3.2.4]
janitorr  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.2.4.jar:3.2.4]
janitorr  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-3.2.4.jar:3.2.4]
janitorr  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-3.2.4.jar:3.2.4]
janitorr  | 	at com.github.schaka.janitorr.JanitorrApplicationKt.main(JanitorrApplication.kt:48) ~[classes/:na]
janitorr  | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jellyseerrService' defined in class path resource [com/github/schaka/janitorr/jellyseerr/JellyseerrConfig.class]: Failed to instantiate [com.github.schaka.janitorr.jellyseerr.JellyseerrService]: Factory method 'jellyseerrService' threw exception with message: Connect timed out executing GET http://192.168.80.2:5055/api/v1/settings/radarr
janitorr  | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1335) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1165) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:904) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:782) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	... 19 common frames omitted
janitorr  | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.schaka.janitorr.jellyseerr.JellyseerrService]: Factory method 'jellyseerrService' threw exception with message: Connect timed out executing GET http://192.168.80.2:5055/api/v1/settings/radarr
janitorr  | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:177) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:644) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	... 33 common frames omitted
janitorr  | Caused by: feign.RetryableException: Connect timed out executing GET http://192.168.80.2:5055/api/v1/settings/radarr
janitorr  | 	at feign.FeignException.errorExecuting(FeignException.java:278) ~[feign-core-13.1.jar:na]
janitorr  | 	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:110) ~[feign-core-13.1.jar:na]
janitorr  | 	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:70) ~[feign-core-13.1.jar:na]
janitorr  | 	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:99) ~[feign-core-13.1.jar:na]
janitorr  | 	at jdk.proxy2/jdk.proxy2.$Proxy81.getSonarrServers(Unknown Source) ~[na:na]
janitorr  | 	at com.github.schaka.janitorr.jellyseerr.JellyseerrRestService.<init>(JellyseerrRestService.kt:31) ~[classes/:na]
janitorr  | 	at com.github.schaka.janitorr.jellyseerr.JellyseerrRestService.<init>(JellyseerrRestService.kt:13) ~[classes/:na]
janitorr  | 	at com.github.schaka.janitorr.jellyseerr.JellyseerrConfig.jellyseerrService(JellyseerrConfig.kt:35) ~[classes/:na]
janitorr  | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
janitorr  | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
janitorr  | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:140) ~[spring-beans-6.1.5.jar:6.1.5]
janitorr  | 	... 34 common frames omitted
janitorr  | Caused by: java.net.SocketTimeoutException: Connect timed out
janitorr  | 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source) ~[na:na]
janitorr  | 	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source) ~[na:na]
janitorr  | 	at java.base/java.net.Socket.connect(Unknown Source) ~[na:na]
janitorr  | 	at java.base/sun.net.NetworkClient.doConnect(Unknown Source) ~[na:na]
janitorr  | 	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:na]
janitorr  | 	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:na]
janitorr  | 	at java.base/sun.net.www.http.HttpClient.<init>(Unknown Source) ~[na:na]
janitorr  | 	at java.base/sun.net.www.http.HttpClient.New(Unknown Source) ~[na:na]
janitorr  | 	at java.base/sun.net.www.http.HttpClient.New(Unknown Source) ~[na:na]
janitorr  | 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source) ~[na:na]
janitorr  | 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[na:na]
janitorr  | 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[na:na]
janitorr  | 	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) ~[na:na]
janitorr  | 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[na:na]
janitorr  | 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[na:na]
janitorr  | 	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[na:na]
janitorr  | 	at feign.Client$Default.convertResponse(Client.java:111) ~[feign-core-13.1.jar:na]
janitorr  | 	at feign.Client$Default.execute(Client.java:107) ~[feign-core-13.1.jar:na]
janitorr  | 	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:100) ~[feign-core-13.1.jar:na]
janitorr  | 	... 43 common frames omitted
janitorr  | 
janitorr  | 
janitorr  |   .   ____          _            __ _ _
janitorr  |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
janitorr  | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
janitorr  |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
janitorr  |   '  |____| .__|_| |_|_| |_\__, | / / / /
janitorr  |  =========|_|==============|___/=/_/_/_/
janitorr  |  :: Spring Boot ::                (v3.2.4)
janitorr  | 
janitorr  | 2024-05-15T14:07:13.491+02:00  INFO 1 --- [           main] c.g.s.janitorr.JanitorrApplicationKt     : Starting JanitorrApplicationKt using Java 21.0.2 with PID 1 (/app/classes started by root in /)
janitorr  | 2024-05-15T14:07:13.495+02:00  INFO 1 --- [           main] c.g.s.janitorr.JanitorrApplicationKt     : No active profile set, falling back to 1 default profile: "default"
janitorr  | 2024-05-15T14:07:15.395+02:00  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8978 (http)
janitorr  | 2024-05-15T14:07:15.416+02:00  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
janitorr  | 2024-05-15T14:07:15.417+02:00  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.19]
janitorr  | 2024-05-15T14:07:15.481+02:00  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
janitorr  | 2024-05-15T14:07:15.487+02:00  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1883 ms


```

Do you know what my mistake could be?

Thank you!

**Comment by Schaka** [comment]
Janitorr can't connect to `http://192.168.80.2:5055/api/v1/settings/radarr`.
Which means either that IP is incorrect, connection between containers is wrong or Jellyseerr is simply not available.

**Comment by Schaka** [comment]
I noticed something now. I don't know your networking setup, so this is completely up to you to figure out.
But notice anything wrong with this URL:
```
http://192.168.1.252:5055//api/v1/settings/radarr
```

There shouldn't be a duplicate slash. Please follow the template properly.
Since network issues aren't in the scope of this project, I'll have to close this.
